### PR TITLE
add spiraling propwash effect (new)

### PR DESCRIPTION
**Pull request by dany93**
see issue #947

### CODE REVIEW

**Comment by onox** [comment]
I have limited knowledge of the FDM, but it seems to work and the code looks fine. Can be merged if no one has any objections.

**Comment by dany93** [comment]
Thanks onox for watching. 
I have prepared a small variant, with:
- a bit more propwash effect,
- and a rudder preset-trim to have the slip-skid-ball centered in cruise.
If you can wait a bit....

**Comment by dany93** [comment]
After reading @tigert comments,
- Increased a bit the spiral propwash effect,
- Added a rudder trim preset, to have the slip-skid-ball centered at cruise.

Your opinions on the propwash effect? The quantity is `Cnspw` <value> (line 1667), 0.01 (weak, previous value) or 0.02 (current proposal). Easy to change later.

**Comment by HHS81** [comment]
@dany93 
Tried it.

I have no reallife experience, just know X-Plane's C172.
In X-Plane the effect is much stronger, especially at very low speeds. When I begin to acclerate, I need half of right rudder, the more speed I gain the less I need. 

Here in FGFS there is a little need of right rudder, but very minor, and not at low speeds.

**Comment by dany93** [comment]
Thank you @HHS81.

This is also my feeling, but I hesitate to set it stronger, because of beginners.
However, at very low speed (almost stopped without brakes) and still at idle, it already starts steering leftwards.

From my memory in URL Ultralights, it is stronger too (I cannot give a value).

**Comment by HHS81** [comment]
@dany93 
I think especially for beginners a realistic, and with that, strong effect should be set. So they can learn, the c172 is still very forgivable.
I'm thinking to implement the propwash to the C182S/T as well.

**Comment by dany93** [comment]
I'm ready to set it stronger.  If others agree...

**Comment by gilbertohasnofb** [comment]
> I'm ready to set it stronger. If others agree...

I do. I am all for trying to simulate the real aircraft as much as we possibly can.

**Comment by dany93** [comment]
Spiral propwash effect made stronger (Cnspw value = -0.05).
Above this strength (e.g. -0.1), the floats and amphibious versions become uncontrollable on the water or on the ground at very low speed. If we wish to make the spiral propwash such stronger, the Cnspw value will have to be conditioned, weaker for these versions. However, that's only a circumventing.
Personally (but that's pure guess) I think that this value (-0.05) can be applied and submitted to practice and observation.

**Comment by onox** [comment]
The changes are OK for me. I need to use more rudder, but I can takeoff and land.

**Comment by dany93** [comment]
Thank you, onox.

**Pull request merged**
