### PR TITLE
Interior upgrades

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #1094

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@wlbragg What do you mean in conjunction? How can I test both? Should I test and merge @ltoenning 's PR first then the same with this one?

**Comment by wlbragg** [comment]
@gilbertohasnofb I was going to use this PR for the next big push and include @ltoenning 's work above. Unfortunately @ltoenning 's work requires a mesh change, thus it attaches to this PR. Both @ltoenning 's PR and this PR would have to be pushed together for it to work.
Did I just complicate this?

**Comment by gilbertohasnofb** [comment]
> Did I just complicate this?

Yes, because I can't just test two branches at the same time. I am sure there must be a way using git to add commits to a PR by an external contributor, I just don't know how. @onox perhaps could advise. Else, I can't see how I could test them together.

**Comment by gilbertohasnofb** [comment]
How did you manage to test them together when you were working on your commit?

**Comment by wlbragg** [comment]
If @onox can guide me on backing this out of here and pushing the mesh work to the other PR I will do that. Then we can use this for all the new stuff.

**Comment by wlbragg** [comment]
>How did you manage to test them together when you were working on your commit?

Because I did the mesh I temporarily made the xml changes to test.  It's such a simple change I don't think it is an issue. We are just removing some necessary pick's and pick objects. And the group naming stuff I verified locally.

**Comment by gilbertohasnofb** [comment]
> Then we can use this for all the new stuff.

If you manage to add your commits directly to that other PR, I would still suggest closing this one and opening a new one else we need to remove your commit from here and all this just complicated things. In particular, we would want the most current mesh for the interior work and this PR is based on the mesh prior to the DME fix. So if you manage to add your commit to that other PR, we delete this branch both in our repo and you do that locally and then you can create a new branch for the interior work.

**Comment by gilbertohasnofb** [comment]
From what I am reading, the only way of doing this would be to clone the fork, push your commits there and then update the PR. See: https://help.github.com/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork/ and https://stackoverflow.com/questions/22237609/adding-to-someone-else-s-pull-request-on-a-github-project-that-i-do-not-own

**Comment by wlbragg** [comment]
@gilbertohasnofb I think the easiest thing to do is for me to take over @ltoenning PR and add that work here. @ltoenning can close that PR and we can continue on from here so you can test everything as we go. That way we can still use this PR for what it was intended for. It already contains the most current master.
In the future, don't we want other contributors to open a branch so we can pull and test? If he had done that to start I could have added my mesh work to it and close it out before opening this PR.

**Comment by gilbertohasnofb** [comment]
The problem with that is that his commits will then belong to you, and I guess some people might care for that. External collaborators are particularly keen in having their contributions directed to them.

> In the future, don't we want other contributors to open a branch so we can pull and test? If he had done that to start I could have added my mesh work to it and close it out before opening this PR.

What do you mean by opening a branch? External contributors don't have write access to our repository which is why they can't create branches here and can only create branches on their forks. 

Let's just maybe wait to hear from @onox, maybe he knows something that I am missing here.

**Comment by wlbragg** [comment]
>What do you mean by opening a branch? External contributors don't have write access to our repository which is why they can't create branches here and can only create branches on their forks.

I didn't know this, now it make sense.

OK, how about you going ahead and merging both, then test (I assure you it is correct), then close the two and I will open a new PR to continue?

**Comment by onox** [comment]
@wlbragg If want to commit changes made by someone else, then you do `git commit --author="Name <e@mail.com>"`

**Comment by onox** [comment]
You could also create a feature branch and then let an external contributor create a PR to that branch instead of `master`.

**Comment by wlbragg** [comment]
@gilbertohasnofb I think we got this back on track. Sorry for the confusion, lesson learned.
We should be able to continue on from here with the rest of the interior work.

**Comment by gilbertohasnofb** [comment]
@wlbragg for the sake of simplicity, what if I test this now, merge it, delete this branch and we start with a clean branch for the rest of the work?

**Comment by wlbragg** [comment]
@gilbertohasnofb that's fine, seeings how I made such a mess out of it. I hope @onox doesn't scold me for the master merge into this. I still am confused how we got a conflict even though I know what the conflict was .

**Comment by gilbertohasnofb** [comment]
Ok, I will test it and merge it now

**Comment by wlbragg** [comment]
I see it, the base is in the animation. Unfortunately I won't be able to fix until later tonight. I'm out of here for awhile.

**Comment by wlbragg** [comment]
@gilbertohasnofb I was able to fix it before I had to get off here.

**Comment by gilbertohasnofb** [comment]
@wlbragg Thanks, I will check it now and merge it if all is fine!

**Comment by gilbertohasnofb** [comment]
Thanks both @ltoenning and @wlbragg, this solved the issue! @wlbragg I deleted the branch as agreed, so please do a git pull on your master and create a new branch for the rest of the interior things.

**Pull request merged**
