### PR TITLE
Mesh update, upgrades and corrections

### LINKED ISSUE #599: Better texture bars for the cockpit of amphibian and pontoon variants
Create a better texture bars for the cockpit of amphibian and pontoon variants. I don't think we should go with a higher resolution image, the bar is already pretty big in the png file. But the bar texture is a bit fuzzy in the png file itself since the source image wasn't the best for this purpose, so maybe if we had a better picture as source I could try to improve it. Maybe @tigert can take some more pictures for us if he still has access to the OH-CTL, if not then we have to find some better source or stick to this current texture.

### LINKED ISSUE #682: The beacon light is colliding with the glass
The beacon light is currently colliding with the glass:

fg

See the discussion here for more info: https://github.com/Juanvvc/c172p-detailed/pull/678#issuecomment-174726479

### LINKED ISSUE #737: Add ALS dirt effect
I toyed with this on the j3cub and it is easy to create. My goal is to make it dynamic as to where eventually it gets dirty enough that our GUI asks if you would like to wash the aircraft. I haven't started that coding even on the cub, but I think it would be relatively easy also. Here is the cub with dirt on the wing, strut and tires.

fgfs-screen-001 22

### LINKED ISSUE #784: Why set parking brake on damaged left/right gear?
``` xml
 <!-- A broken gear operates as a parking brake -->
 <property>/fdm/jsbsim/gear/unit[1]/broken</property>
 <property>/fdm/jsbsim/gear/unit[2]/broken</property>
```

I ask because we extend contact points 7 and 8 to be the WOW points and they have their own friction factors?

### LINKED ISSUE #956: Reduce reflections, particularly on the propeller
I think the propeller is really too shiny now, as it seems to use the same coefficients as the fuselage. But it seems to me that in RL the propeller is quite matte:

As a side note, perhaps our fuselage is also a bit too shiny? Even under sunlight a white 172 is also quite matte:

### LINKED ISSUE #968: Improve air intake textures
Improve air intake textures:

### LINKED ISSUE #969: Add cables to rudder
Add cables to rudder using these as reference:

### LINKED ISSUE #975: Improve VHF antenna models
Improve VHF antenna models:

fg-5

### LINKED ISSUE #982: Tires should not be reflective
Tires should not be reflective as it makes them look metallic:

fg

### LINKED ISSUE #983: Improve matching of fuselage texture
The fuselage textures of all liveries are having some matching issues, some shades do not match when two parts are stitched together and some artifacts are also being shown.

### LINKED ISSUE #984: Nose wheel buried in the ground
36568656-6a3e6032-17f0-11e8-9a11-48ba9327db46

### PR DESCRIPTION
**Pull request by wlbragg**
* Fixes #682 
* Fixes #975 
* Fixes #982 
* Fixes #984 
* Fixes #956
* Fixes #969
* Fixes #784
* Fixes #968
* Fixes #983
* Fixes #599

Includes initial setup of ALS dirt effect issue #737 

* Finished as far as I am concerned.

### CODE REVIEW

**Comment by wlbragg** [comment]
I fixed some texture and UV mapping issues. The antenna,  landing and taxi lights are visible in  these screenshots. 
fgfs-screen-005
fgfs-screen-003

**Comment by wlbragg** [comment]
There was a couple small particle effect fixes left to do so I did it her. This will get rid of another issue. It wasn't worth making a new PR for such a small thing.

**Comment by gilbertohasnofb** [comment]
@wlbragg sorry for my stupidity but I loaded this in the sim and the edge doesn't have any dirt on it. Do I need to change some property in order to activate the effect?

**Comment by wlbragg** [comment]
>Do I need to change some property in order to activate the effect?

Yes, use any or all of the following properties in the property tree
environment/aircraft-effects/edge-dirt
environment/aircraft-effects/wing-dirt
environment/aircraft-effects/fuselage-dirt
environment/aircraft-effects/tail-dirt

They are floats with values from .1 to at least 3.
I don't remember exactly how the value effects it. You'll have to experiment with it.

**Comment by gilbertohasnofb** [comment]
> I suppose I need to set up something to make it easier to test the glass effect too if you want to work on bug splatter or cracks on the windshield.

This way you described above is easy enough. I will check this and work on it as soon as I have some free time, possibly on Thursday.

**Comment by wlbragg** [comment]
After much pain I managed to get the blend and ac files in this branch to match master.

I don't ever want to do that again, I think I learned my lesson, do all the blend work in the same branch. So anyone working on the c172p.blend needs to use this branch and we can't be diverging the mesh at the same time or we are going to have trouble.

**Comment by wlbragg** [comment]
I went through an made sure all major exterior mesh "fuselage, wings, struts, tail" were all using the same material. I think I notice a difference. It's looking good to me!
I also UV mapped a couple of the antennas again. I thin k the exterior is looking really sharp now with some decent contrast to the different equipment surfaces.

**Comment by onox** [comment]
> do all the blend work in the same branch. So anyone working on the c172p.blend needs to use this branch and we can't be diverging the mesh at the same time or we are going to have trouble.

1 branch + 1 person. You can't have 2 persons working on the same file at the same time because if person A commits first and then person B commits, B might override changes done by A. Unless B starts after A has committed his changes.

Basically what you need is a token. You grab the token from the table, hold it in the air and you shout that you have it. Then you work on the blend file. After you have committed everything you place the token back on the table for someone else to grab it :)

**Comment by wlbragg** [comment]
>we can't be diverging the mesh at the same time 

Yes, I understand completely, especially when I did it to myself.

I have a system in mind for this.

If we create a branch like "mesh" and only use it to make any mesh and ac changes and use an open PR as the "token, I think we could avoid any potential trouble.
Basically, if there is an open PR for branch "mesh" then someone is currently working with the mesh and others need to wait until the PR is merged and closed.

**Comment by onox** [comment]
That could work, but you would have to make sure merge master to the `mesh` branch before you start working on it.

Or maybe we could use the labeling system on Github? Make sure that only 1 issue has the "working-on-mesh" label.

**Comment by wlbragg** [comment]
>Or maybe we could use the labeling system on Github? Make sure that only 1 issue has the "working-on-mesh" label.

You'll have to explain that to me. Can you readily see the issue that has that label?

>you would have to make sure merge master to the mesh branch before you start working on it.

Not really because that branch is always current, it is the only branch that your allowed to work on the mesh in.

Can you create a branch with just a Blend and ac and no other files and still use it to merge to master?

**Comment by onox** [comment]
For example: https://github.com/c172p-team/c172p-detailed/issues?q=is%3Aissue+is%3Aopen+label%3Asound

> Not really because that branch is always current, it is the only branch that your allowed to work on the mesh in.

Do you mean you recreate the branch everytime?  I'm still concerned that there's no issue number in it. Makes it difficult to lookup the corresponding issue on Github.

> Can you create a branch with just a Blend and ac and no other files and still use it to merge to master?

Yes, by making sure you only `git add` .blend and .ac files?

**Comment by wlbragg** [comment]
>Make sure that only 1 issue has the "working-on-mesh" label.

I like the simplicity, we just all need to know this is how we're going to do it from now on.

**Comment by onox** [comment]
Lets try it and see if it works. Would you like to create the label?

**Comment by wlbragg** [comment]
Like so?

One problem I am having now is I did some blend work in this PR and it is not related to the dirt effect at all and I really want to get it in to master asap. But I guess I have to wait until this PR is merged. I guess that is my only argument for having a branch that is separate from any issue. But that is a problem unto itself.

**Comment by onox** [comment]
> Like so?

Yes. Or attach it to the issue, whatever you find easier.

**Comment by wlbragg** [comment]
ant
ant2

**Comment by gilbertohasnofb** [comment]
@wlbragg new VHF antennas and beacon fix are wonderful, many thanks.

**Comment by wlbragg** [comment]
The smoothness setting in Blender is very important and here's why...
smoothtes

Which of these setting do you like better, in this case the best looking on has the lowest smoothness setting of 35deg the other two are 85 and 180. You could do this comparison with virtually every object to decide what degree it should be.

**Comment by gilbertohasnofb** [comment]
@wlbragg In this particular case I think the lowest smoothness looks better, but that's my opinion. Feel free to override it any time since you are the 3D modeller :smile:

**Comment by wlbragg** [comment]
I know this is a pain but I think it is something we really should look at. Her is 4 different settings for the specular fix. We have shininess set at 128. The lowest setting here is 64.
It goes  64, 96, 116, 120, 128.
test

**Comment by wlbragg** [comment]
Here is our aircraft with no specular fix at all. Only what is in the .ac.

**Comment by gilbertohasnofb** [comment]
> I know this is a pain but I think it is something we really should look at. Here is 5 different settings for the specular fix. We have shininess set at 128. The lowest setting here is 64.
It goes 64, 96, 116, 120, 128.

As I wrote before, my opinion is that our current shininess is a bit too much. I much prefer those lower settings in your sequence above.

Else our airplane start to look like this :stuck_out_tongue_closed_eyes:

**Comment by gilbertohasnofb** [comment]
I think 116 is the better one, though it's difficult to judge from the screenshots.

**Comment by legoboyvdlp** [comment]
To be honest, I personally prefer the lowest setting, the image before the beacon goes on... but you are the 3D experts here :)

116 does look decent, fairly ahiny without looking like bare metal.

Would kt be possible for shininess to be adjustable per livery...?

**Comment by wlbragg** [comment]
>Would kt be possible for shininess to be adjustable per livery...?

Yes, I think so.

I just pushed what I think is the best overall settings for the exterior. I'm not saying there isn't' individual objects that might not have better settings, but overall I think this is pretty good. It also seems to hide a lot of the irregularities and imperfections in the mesh.

**Comment by gilbertohasnofb** [comment]
> Would kt be possible for shininess to be adjustable per livery...?

I don't think that's necessary, we don't have any metallic livery. They all should fit well with a single setting, so let's just try to pick the best one.

**Comment by gilbertohasnofb** [comment]
@wlbragg I like the new settings and I am quite happy to keep it this way -- what do you think about it?

By the way, I noticed a problem with the UV-mapping of the tips of the wings: many liveries, particularly the HD ones, have some small details in the tips of their wings which now disappeared or are simply looking different. Could you please take a look at it?

**Comment by gilbertohasnofb** [comment]
I am adding screenshots here. Before the new wing, as the textures were intended:

fg-5
fg-6
fg-7
fg-8
fg-9

After the new wing:

fg-0
fg-1
fg-2
fg-3
fg-4

**Comment by wlbragg** [comment]
To be quite honest I am afraid this is over my head. I knew you'd eventually catch this :rofl:
The mapping of the wings is done in a manner I am unfamiliar with. Still many parts of Blender procedures I simply don't know how to do. Maybe we could get someone with an actual Blender skill set to look at it and show us how to do it. Long story short, I fudged it!

**Comment by gilbertohasnofb** [comment]
@wlbragg I completely understand it, no worries. Perhaps @HHS81 could give us a hand understanding how to UV-map the tip of these new wings?

**Comment by gilbertohasnofb** [comment]
@wlbragg I really love the new flaps, both the model and the animation look gorgeous, great work! 

But I noticed that a lot of objects lost their textures in this last update, e.g. tires, exhaust pipe, etc.

fg

**Comment by wlbragg** [comment]
>a lot of objects lost their textures in this last update

Interesting, I was using the 26 inch tires and they are OK. It's just the default tires. I'll fix it here in a bit.

**Comment by gilbertohasnofb** [comment]
@wlbragg there might be other objects as well, look at the air intakes by the side of the propeller cones, they also seem white in my shot above

**Comment by wlbragg** [comment]
Oops, don't know how or why I merged master into this but I guess that is not a real problem?

@onxo, @gilbertohasnofb 
After a review of work completed to date with this PR can we merge it into master and I'll open a new PR to continue with a new round of work?

**Comment by gilbertohasnofb** [comment]
> Oops, don't know how or why I merged master into this but I guess that is not a real problem?

I think this is not too difficult to clean up, perhaps @onox can give us a hand.

> After a review of work completed to date with this PR can we merge it into master and I'll open a new PR to continue with a new round of work?

This PR is gigantic and I would like to have it merged as soon as possible, possibly after we finish working on the rudder cable. What do you think, is there anything else missing? I opened a new issue of that wing tip uv-map issue since you mentioned you didn't know how to properly fix that, so I guess we can postpone it a bit.

**Comment by wlbragg** [comment]
>This PR is gigantic and I would like to have it merged as soon as possible, possibly after we finish working on the rudder cable. What do you think, is there anything else missing?

I agree, one the rudder is considered "done" we should merge and start a new PR.

It's too difficult for me to open a PR for every mesh job I do because of the binary and I will loose valuable time if I have to wait for one category of issue to be completely wrapped up before I proceed to the next issue. Thus why I am doing it this way. While I wait for you or @onox to review one job I can start on the next. I can't do that with multiple PR's going at the same time editing a single binary.

**Comment by gilbertohasnofb** [comment]
> It's too difficult for me to open a PR for every mesh job I do because of the binary and I will loose valuable time if I have to wait for one category of issue to be completely wrapped up before I proceed to the next issue. Thus why I am doing it this way. 

I am not criticizing you by any means, I completely understand your reasoning. I just meant to say that we can try to merge what we have asap and then continue with a new PR.

**Comment by wlbragg** [comment]
>I am not criticizing you by any means, I completely understand your reasoning. I just meant to say that we can try to merge what we have asap and then continue with a new PR.

I didn't think you were criticizing me. I feel guilty or funny about the way I am doing this, so I was trying to justify it. . But this many mesh changes would take forever if we had to wait on each one.
I am in complete agreement, we need to hold and merge as soon as we can, then I can get on another roll.

**Comment by gilbertohasnofb** [comment]
Sigh... I think I have messed up the rebasing... :man_facepalming: Those commits I wanted to remove have not been removed and some copies of other commits... I am sorry @wlbragg but I think I will need to wait for @onox to help us fix this one. My apologies.

@onox The last three commits are copies of other commits which were doubled by accident and should be removed. I am talking about:

```
new propeller textures   03dfaa0
Add rudder ports to liveries, remap propeller   c78c6a5
Make inside faces on rudder cable ports and remap for shadow   5c08ed4
```

The original ones should of course be kept. The commits I was trying to remove from the branch were...
```
shadow texture for rudder cable   a415097
Merge branch 'issue-737' of https://github.com/c172p-team/c172p-detai…   ae8731e
Remap rudder cable ports to new black texture   2fdbf5d
```

... while keeping `Make inside faces on rudder cable ports and remap for shadow   0320fb8`

**Comment by onox** [comment]
@gilbertohasnofb I don't see the 3 original commits you're referring to.

**Comment by gilbertohasnofb** [comment]
@onox gosh, it actually looks like I did not mess it up, perhaps it was just the case of refreshing this very page. After rebasing I was still seeing those older commits. Anyway, so now I don't see any duplications and the ones I intended to remove are indeed removed, so it seems we are good to go, right?

If that's the case, then I think @wlbragg just needs to do a `git fetch` and continue working, correct?

**Comment by onox** [comment]
Is what you see on Github okay?

**Comment by onox** [comment]
If the last commit on @wlbragg's computer is `Make inside faces on rudder cable ports and remap for shadow   5c08ed4` then he can continue working.

**Comment by gilbertohasnofb** [comment]
> Is what you see on Github okay?

Yes, I believe it is all okay now.

> If the last commit on @wlbragg's computer is Make inside faces on rudder cable ports and remap for shadow 5c08ed4 then he can continue working.

Remind me again, how does one check the most recent commits in a local branch?

**Comment by onox** [comment]
`git log`?

**Comment by onox** [comment]
Or `git rev-parse HEAD`

**Comment by onox** [comment]
If everything looks ok on your computer and the issues in the first comment have been fixed, then we can merge this PR.

**Comment by gilbertohasnofb** [comment]
Thanks again, @onox, and apologies for the confusion.

> If everything looks ok on your computer and the issues in the first comment have been fixed, then we can merge this PR.

We are just missing a couple of details before being able to merge this, but we are almost nearly there. I think tomorrow we could merge this.

@wlbragg we are all good to continue then. Just to make sure there are no more issues, I will wait for you to confirm all is fine on your side before continuing doing any work. Tomorrow I will create the matte version of the backside of the propellers if all is okay and we can see if that improves the reflection issue we have been discussing. Also, please test if this branch in its current status has all your recent work and modifications and that I did not remove anything important by accident. It's all looking good from my side, but I would be glad if you would double check it as well.

**Comment by gilbertohasnofb** [comment]
@wlbragg one more thing, I found an issue with the uv-mapping of the flap after you created the new model, see:

fg

**Comment by wlbragg** [comment]
This is what I show...
git

**Comment by wlbragg** [comment]
The above is where I left off. Do I need to fetch?

**Comment by wlbragg** [comment]
>I found an issue with the uv-mapping of the flap after you created the new model,

:+1:

**Comment by gilbertohasnofb** [comment]
> The above is where I left off. Do I need to fetch?

I think so, @onox can you confirm this? Does he need to do anything else?

**Comment by wlbragg** [comment]
@gilbertohasnofb 
Because I still have
~~~
shadow texture for rudder cable   a415097
Merge branch 'issue-737' of https://github.com/c172p-team/c172p-detai…   ae8731e
Remap rudder cable ports to new black texture   2fdbf5d
~~~
I am going to backup my repo and just pull the whole thing again, takes all of 2 minutes here. Then I should be in sync with the what we have on git and all I should have to do concerning the rudders is map the rudder cable ports back to the original spot on the fuselage and were done with it. I'll fix the flaps mapping issue tonight. Tomorrow you can finish the matte version of the backside of the propellers and we'll double check that this meets our needs and we can merge and start over again. Thanks!

**Comment by wlbragg** [comment]
I'm all set here and in sync with the the development repo.

**Comment by onox** [comment]
Btw, @wlbragg I sometimes notice that you have some local commits and then when you do `git pull` you get a merge commit. If you do `git pull --rebase` instead it will pull in the changes made by others and put your local commit on top of it. That will avoid those "Merging branch X into X" commits. Just a little trick.

It's what I do with fgdata. I have some local fixes (that I can't upstream) committed to my fgdata repository on my computer. Whenever I want to bring in the stuff from upstream, I do `git pull --rebase origin next` and then it pulls in the changes from origin/next and put my local commits on top of those. I can do this hundreds of times and get 0 merge commits. Because my commits always remain on top I can easily chop them off if I ever decide I don't need them anymore.

**Comment by wlbragg** [comment]
> If you do git pull --rebase
That will avoid those "Merging branch X into X" commits. Just a little trick.

I need to get away from the Git GUI I use and start using the command line so I can use these features of git. There are so few commands that I regularly use, I am sure it would take no time at all to be proficient at it.
Seems simple enough. in fact opening the gui from the terminal probably takes more time than simply using the --rebase switch.

I'll try to do this in the future, thanks.

**Comment by gilbertohasnofb** [comment]
Ok, I just pushed a bunch of texture fixes now including:

- new air intakes, fixing #968
- improve matching of fuselage texture in the back of the plane, fixing #983
- matte propeller, front and back, applied to all liveries

I did this in a single commit since they were all affecting the same png files.

@wlbragg from my side that was it. Are we missing anything from your side or can we merge this?

**Comment by onox** [comment]
- The backside of the propeller still looks black (front side looks grey)
- The bottom part of the tail isn't aligned with the fuselage for certain liveries (PT-IAO, N6575E, N35799, KLM, G-BEMB)

**Comment by gilbertohasnofb** [comment]
> The backside of the propeller still looks black (front side looks grey) (OH-CTL, PT-IAO, ZS-MDF)

That's a feature, the real propeller is black on the backside to avoid reflecting light into the pilot's eyes. It is now mapped to a different texture than the front of the propeller, which is different for each livery according to the reference photos of each of them.

> The bottom part of the tail isn't aligned with the fuselage for certain liveries (PT-IAO, N6575E, N35799, KLM, G-BEMB)

@wlbragg would you mind taking a look at this?

**Comment by wlbragg** [comment]
Yep, sorry for the delay, I just saw this. For some reason It didn't pop-up as a new post on my end. Doing it now

**Comment by wlbragg** [comment]
Nice job catching all the issues with the liveries. A lot if not all of that was caused by my mesh work. Thanks for catching. While I was in there doing the rudder, I noticed the back side of the VS was not scaled correctly so I fixed it.

OK, I'm all done. We should be good to merge. Looking really good IMHO!

**Comment by gilbertohasnofb** [comment]
@wlbragg I just pushed a improved texture for the tail of the OH-CTL as after your fix all other liveries were matching perfectly from the back view except for that one, and so not to mess with them I decided to fix it in the texture itself.

Finally, I noticed a small issue with the UV-mapping of the bump map, there are some distorted bolts on top of the rudder, see:

fgfs-screen-003
fgfs-screen-004

Could we fix that and then merge this?

**Comment by gilbertohasnofb** [comment]
@wlbragg sorry, decided to do another small fix I wanted for a long time: I created a much better cockpit bar for the float variant, the previous one was really low res. See the new one:

fg-1

But I need help fixing the UV-map. See how the joining is not looking good below, could you please invert the UV-map of the half pointing _away_ from the pilot's point of view, i.e. side A in my image below?

 
fg-0

**Comment by gilbertohasnofb** [comment]
If 'inverting' half of the uv-map doesn't sound clear, let me know and I can make a diagram or something. Sometimes it's difficult to express something involving 3D modelling

**Comment by wlbragg** [comment]
>I noticed a small issue with the UV-mapping of the bump map, there are some distorted bolts on top of the rudder,

As far as I can tell that is not anything but reflection. In the UV map there was some dark texture area in the way , so I moved the mapping a little bit to get it off the dark texture area. But that is all that I can do there. Unless your talking about something else?

rud

rud1

rudd

**Comment by gilbertohasnofb** [comment]
The rudder top looks good to me!

**Comment by gilbertohasnofb** [comment]
> But I did notice this with the beacon light switch ..

That's a feature, some liveries have that and others don't. it's to simulate what is commonly found out there: home made replacements of toggles!

**Comment by gilbertohasnofb** [comment]
PT-IAO, OH-CTL, N35799 and most, but not all, lower resolution liveries use that.

**Comment by wlbragg** [comment]
OK, I made some finishing touches to the pontoons that I overlooked. Same lighting and smoothness corrections we made to the fuselage and tires.Please revive in sim if you get a chance.
Also, flipped the UV-map of the support bracing and touched up the top of the rudder and VS.

If that is all OK, I think were done!

**Comment by gilbertohasnofb** [comment]
@wlbragg two issues:

fgfs-screen-001

fgfs-screen-002

About the cockpit bars, this is what I had in mind for the UV-mapping. Suppose the texture is a gradient from green to red:


untitled

**Comment by wlbragg** [comment]
OK, pontoon bracing is done. Sorry I didn't understand what it was you wanted the first time around.

Looking at the OH-CTL mapping now. I am petty sure I know what that is.

**Comment by wlbragg** [comment]
All done!

**Comment by onox** [comment]
@wlbragg Is the interior effect applied to the cockpit bars? It doesn't look like it gets any shadow unlike the dashboard itself.

**Comment by wlbragg** [comment]
>Is the interior effect applied to the cockpit bars?

No, it wasn't. It is now along with the pontoon rudder deploy objects on the cabin floor.

**Comment by wlbragg** [comment]
I cleaned the Ski's effects up like I did the pontoons.

**Comment by onox** [comment]
The left bar as well?

**Comment by onox** [comment]
It seems so, just more difficult to see.

**Comment by onox** [comment]
I don't see the errors you're talking about.

**Comment by onox** [comment]
If @gilbertohasnofb is OK with it then he can merge the PR when he comes online.

**Comment by wlbragg** [comment]
Hum, OK then, It may be my local configuration. A clear indicator is when I start the c172p and neither engine is selected. That usually requires the aircraft cache to be cleared to fix it. That's currently happening so it's probably something on my end.

**Comment by wlbragg** [comment]
Hum, OK then, It may be my local configuration. A clear indicator is when I start the c172p and neither engine is selected. That usually requires the aircraft cache to be cleared to fix it. That's currently happening so it's probably something on my end.

**Comment by gilbertohasnofb** [comment]
I don't see any errors either, and everything looked good from my side (all last issues have been fixed) thus I am merging this.

**Comment by gilbertohasnofb** [comment]
@wlbragg Fantastic work, really. We basically have a new aircraft :clap: :tada:

**Pull request merged**
