### PR TITLE
Fix issue #751

### LINKED ISSUE #751: Instrument knobs are too short
It seems to me that our instrument knobs (AI, altimeter, HI, etc.) are too short when compared to RL ones. See for instance:

And compare them to:

fgfs-screen-001

### PR DESCRIPTION
**Pull request by legoboyvdlp**
Fixes #751

### CODE REVIEW

**Comment by onox** [comment]
Just one tiny comment: use the word "Fixes" (I think "Closes" should work too) instead of "Fixed issue". Otherwise Github doesn't detect that it needs to link the PR to the issue. You'll see that it underlines the word "Fixes" and the tooltip tells you it will close the linked issue.

**Comment by legoboyvdlp** [comment]
:) Thank you! 

Hopefully Wlbragg will be able to make sure I did this right and merge it... :)

**Comment by wlbragg** [comment]
I'll check it and merge it in a little bit.

Thanks for doing this @legoboyvdlp

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp Thanks for working on this. I checked it and it looks much better than what we have at the moment, but I feel that the knobs are still not long enough. Compare this screenshot of your branch with the photograph below:

fgfs-screen-001



And by the way, when creating PRs it's normally helpful to add not only what @onox mentioned about "Fixes #xxx" but also some few words of what the tester should look for, so that the person reviewing does not need to read through very long discussions in the issues. So for instance in this case "elongates instrument knobs, in particular for the AI, HI, etc."

**Comment by legoboyvdlp** [comment]
Right... I can do that quickly tomorrow morning. I personally feel the AI knobs are the right length, so if you don't mind I'll leave them alone, unless you disagree.

**Comment by legoboyvdlp** [comment]
fgfs-screen-067
@gilbertohasnofb 

How does this look?

**Comment by gilbertohasnofb** [comment]
> How does this look?

I think that looks really good! Have you pushed your modifications to your branch? I haven't been able to pull them.

**Comment by legoboyvdlp** [comment]
I didn't, waiting to see if I had to amend them. Sorry!

**Comment by legoboyvdlp** [comment]
There we go ;)

**Comment by gilbertohasnofb** [comment]
These are now looking great, thanks for the fix!

**Comment by legoboyvdlp** [comment]
Glad to be of help :)

**Pull request merged**
