### PR TITLE
Increasing range of rotation of the yoke animation

### LINKED ISSUE #936: Yoke animation: roll should be +/- 90deg ?
itOuchpods posted in the forum that the yoke animation should turn +/- 90 deg in roll amplitude.
Can someone confirm? (should be easy to fix, there is only to agree).
[itOuchpods post for 90 deg](https://forum.flightgear.org/viewtopic.php?f=4&t=25157&p=319130&sid=da1951e8b1e3c049353e446c90b60f49#p319075)

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
Closes #936

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@dany93 if you want to take a look at this, it's a simple fix and it's ready to be merged.

**Comment by dany93** [comment]
Right, it works as expected.

**Comment by gilbertohasnofb** [comment]
@dany93 So then you can click on the big green button to merge this :smile:

**Comment by gilbertohasnofb** [comment]
@dany93 well, you should then be given the authorization to do that. Both onox and I are a bit away with other projects and RL, so it's not good if we would be the only ones able to merge PRs.

**Comment by gilbertohasnofb** [comment]
@dany93 Strange, you seem to have full write access so I thought you should be able to merge PRs. @wlbragg you are able to merge PRs, correct? If so, then I don't know what setting is preventing Dany as to me you both have identical settings in the c172p-team group. Perhaps @onox knows better.

**Comment by wlbragg** [comment]
Sorry for the late reply, as far as I can tell, yes , I can merge at least some PR's including this one..

**Comment by gilbertohasnofb** [comment]
Thanks for the info, @wlbragg. So then we have to figure out why @dany93 can't do the same, as you seem to both have identical privileges in this repository. If @onox could take a look at this I would really appreciate, perhaps I am missing some small different settings between those two user settings...

**Comment by wlbragg** [comment]
I didn't actually try it, but I noticed it basically implied I could if I wanted to. I don't know though if I actually tried it if it would then tell me I am not authorized. I remember not being able merge once on something, but that may have had a special setting to not allow me to either because of a change request or maybe because I was the person asking for the merge?
I'm sure @onox can answer these question, where oh where can he be 😆

**Comment by onox** [comment]
@c172p-team/developers Organization and repository owners can always push. In addition I've added @wlbragg to the list of people who can push.

**Comment by gilbertohasnofb** [comment]
@onox would you mind then adding @dany93 to that list of people who can push as well? Given that both you and I are quite busy with other projects and RL, at the moment it's only wlbragg who is able to merge PRs. I think it would be really ideal if Dany would join that list.

**Comment by onox** [comment]
@dany93 You can now merge PR's.

**Comment by gilbertohasnofb** [comment]
@onox Thanks a lot!

**Comment by dany93** [comment]
Thank you, @onox and @gilbertohasnofb for the trust.

**Pull request merged**
