### PR TITLE
kx165-2-regression

### LINKED ISSUE #1101: Regression issue: NAV2 standby & active frequency readout not displayed
Currently only displays 000.000 in the digital readouts.

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #1101 

Forgot to export kx165-2.ac in "Correct automatic Blender versioning error in kx165-2"
Thank you @mathieugouin for catching this.
This should be ready to merge after testing and verification.

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@wlbragg There is still a problem. When you scroll the large knob to change the stand by frequency, it flicks between 100 and 110. I suspect someone changed the value of the delta caused by a rotation of that knob to be 10 instead of 1.

**Comment by onox** [comment]
The problem is that `kx165-2.ac` contains "NavStby1M." (notice the dot at the end)

**Comment by gilbertohasnofb** [comment]
The radios are not fine but this branch breaks the flap texture for some reason.

fgfs-screen-003

**Comment by wlbragg** [comment]
Geez! There is a mistake in the commit history. Either i need instruction on how to remove that 2nd commit called kill, or I need to cancel this PR and start over.

**Comment by wlbragg** [comment]
@onox can I do a git reset hard at the prior commit, do my correct commit, then force push?

**Comment by wlbragg** [comment]
@gilbertohasnofb  see, we don't need @onox anymore, he can retire now!
Pleas test and verify all is well!

**Pull request merged**
