### PR TITLE
Bug 876: Modify bumpspec for fresnel effect

### PR DESCRIPTION
**Pull request by onox**
Using the fresnel settings from https://github.com/c172p-team/c172p-detailed/issues/876#issuecomment-264672126

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@onox I am still a bit undecided about this effect. From some angles, it looks stunning, this effect on the fuselage in front of the door is really mind blowing:

fg-6

But from others, it looks bad IMO. Look at the colours from the default angle in the external view:

fg-0

Or compare this sequence:

fg-1

fg-2

fg-3

And here look at the colour of the ailerons and flaps:

fg-5

**Comment by gilbertohasnofb** [comment]
To make myself clear:

- I think the colours get way too washed out from shallow angles
- the amount of grey/opaque green tint that is added on those angles is also too high

**Comment by HHS81** [comment]
@gilbertohasnofb 
amount of green tint: Sure, it doesn't use the cubemap I used in my images. Like in real life the environment decide how it looks

Use this instead:
`			<texture n="5">
				<type>cubemap</type>
	<images>
			<positive-x>Aircraft/Generic/Effects/CubeMaps/buildings/N.png</positive-x>
			<negative-x>Aircraft/Generic/Effects/CubeMaps/buildings/S.png</negative-x>
			<positive-y>Aircraft/Generic/Effects/CubeMaps/buildings/W.png</positive-y>
			<negative-y>Aircraft/Generic/Effects/CubeMaps/buildings/E.png</negative-y>
			<positive-z>Aircraft/Generic/Effects/CubeMaps/buildings/U.png</positive-z>
			<negative-z>Aircraft/Generic/Effects/CubeMaps/buildings/D.png</negative-z>
            </images>
			</texture>`

Btw. this is how X-Plane 11 looks ( I tried it today). Same settings like our Fair Weather at noon at KSEA:

cessna_172sp_3
cessna_172sp_4

**Comment by HHS81** [comment]
Same settings as on the PR, but with suggested Cubemap:
fgfs-screen-008
fgfs-screen-009

And as we can see: FGFS doesn't use PBR, so it looks completly different.
fgfs-screen-010

**Comment by onox** [comment]
@gilbertohasnofb I've changed the cubemap, it should be less green now.

**Comment by gilbertohasnofb** [comment]
@onox It's much better, but I am still not really convinced by the effect, the view from the back still looks strange, see:

fgfs-screen-001

This is quite evident with the liveries that are not predominantly white like PT-IAO or N35799.

Also notice that the effect is not being applied to the very back tip of the fuselage:

fgfs-screen-001 copy

@HHS81 

> Btw. this is how X-Plane 11 looks ( I tried it today). Same settings like our Fair Weather at noon at KSEA:

Yeah, that sim does look pretty, they really raised the bar with this new release. I have been watching some videos of the sim (my computer is too slow to try it) and the illumination is incredible.

> And as we can see: FGFS doesn't use PBR, so it looks completly different.

Yes, I know. This effect we are working on applying here with this PR is very nice and it's a welcome addition to FG, it's just that from a specific angle it doesn't look good, and the problem is that this angle is the very default one when going to external view :cry:

**Comment by HHS81** [comment]
For me it looks correct,  it is the model which doesn't look good. No problem of the shader itself. Such shader really showing the issues of an 3d- Model. And the 3d-model is the Problem here.

The other things which might makes it looks strange is the static cubemap. We would need a dynamic cubemap which shows the present environment.

**Comment by onox** [comment]
> Also notice that the effect is not being applied to the very back tip of the fuselage

The back of the fuselage is part of the `fuselage_` object, to which the bumpspec effect applies. So it might be that there's something wrong with the UV mapping. But like @HHS81 said, the 3D model doesn't look very good and it is in need of a serious upgrade.

**Comment by onox** [comment]
Pontoons looks weird too:

fgfs-screen-016

**Comment by HHS81** [comment]
@onox 
Yes, because the effects inherits from the fuselage-effect which has a normalmap enabled.
`    <normalmap-enabled type="int"> 1 </normalmap-enabled>`
While for the fuselage is a normalmap available and uvmapped,  for the pontons there is no normalmap, so that's why have this strange effect.

The pontons need an own effect, and does not use the bumpspec-fuselage.eff.
I new issue is on the way.

**Comment by HHS81** [comment]
New issue for the pontons: #891

**Comment by gilbertohasnofb** [comment]
@onox Are you really sure that the part `fuselage_1` is the correct object, and if so that the effect is really applied to it? I change the camera angle but it seems that object is not affected at all by the effect. And I don't understand what you mean by perhaps something being wrong with the UV-map of that object, if the object is textured (which it is) then the UV map was properly done, right?

@HHS81 I agree wholeheartedly that our model isn't looking good in some areas, and in particular the back of the fuselage has some problems. But everything I spoke so far is about the effect, not the model: the amount of reflection, the desaturation of the liveries, the grey/green tint that is added, etc. I believe the shader is doing what it's supposed to do, but I can't say I completely like the effect as viewed from behind, it doesn't look natural at to me, and I don't think _that_ is the fault of the model. But I don't think it's too bad either, and the effect works well from other angles, so it's up to you all if you think this is ready to be merged.

As for the pontoons, I think we should either fix in this very PR the rendering bug that @HHS81 as reported in the new issue, or we should try to remove the effect of the pontoons for the time being until we tackle that issue. What do you two think?

@onox 

> the 3D model doesn't look very good and it is in need of a serious upgrade.

Just for the record, if anyone ever gets to do that, I wouldn't mind redoing the textures from scratch once again, I think it would totally be worth it.

**Comment by gilbertohasnofb** [comment]
@onox 

> the 3D model doesn't look very good and it is in need of a serious upgrade.

Just for the record, if anyone ever gets to do that, I wouldn't mind redoing the textures from scratch once again if necessary (in case of a complete new model), I think it would totally be worth it. Though I think there is a lot of room for improvements in the current model.

**Comment by HHS81** [comment]
> Are you really sure that the part fuselage_1 is the correct object, and if so that the effect is really applied to it? I change the camera angle but it seems that object is not affected at all by the effect. And I don't understand what you mean by perhaps something being wrong with the UV-map of that object, if the object is textured (which it is) then the UV map was properly done, right?

It doesn't seem that this part is affected by the effect. And yes, if vertices are overlaying in the uvmap the shader won't like it and produce something like that.

> the amount of reflection, the desaturation of the liveries, the grey/green tint that is added, etc. I believe the shader is doing what it's supposed to do, but I can't say I completely like the effect as viewed from behind, it doesn't look natural at to me, 

As I said: 
1.) we use a static cubemap which shows an environment which does not match the environment actually is around the aircraft. That makes it looks strange. 
2.) X-Plane uses PBR - pyhsical based rendering/ shading. It is a physically based method to create photorealistic images in runtime. So in low, less bright light (dawn, dusk) we see more reflections than in high, bright light (noon). It also depends on the brightness of the environment, near objects etc.....
Our shading isn't physically based. The sky colors may be, but not the whole lighting.

**Comment by HHS81** [comment]
@gilbertohasnofb  about 2.) - another screenshot of X-Plane 11 with Default Cessna 172SP, fair weather (equal settings like FGFS), today,12PM, 34R, KSEA

That's the Aircraft:
cessna_172sp_10

And that's the same aircraft from the back:
cessna_172sp_9

Notice how the color of the aircraft dissapear behind the reflected environment ...

**Comment by gilbertohasnofb** [comment]
@HHS81 :+1::+1::+1:

**Comment by wlbragg** [comment]
Our effect also does that to some extent!
I spent a little time trying out the different reflection cubes we have in fgdata/aircraft/generic to see if there might be a better choice. I think the building or blue-sky-faces are the most appropriate. I think @HHS81  has it tuned in about as good as it is going to get. Or mesh needs some TLC.

**Comment by onox** [comment]
I have rebased the commits on top of `master`.

**Comment by onox** [comment]
Is there anything that prevents this PR from being merged?

**Comment by gilbertohasnofb** [comment]
> Is there anything that prevents this PR from being merged?

Bump (pun intended): can this be merged or does it need some more work?

**Comment by HHS81** [comment]
@gilbertohasnofb 
Hmmm.... there might be change coming on the reflectionshader  :worried:
I found out why the reflection are getting a grey color. I proposed a fix, but Thorsten and me are unsure ho to proceed.

**Comment by onox** [comment]
Assuming Thorsten and @HHS81 aren't going to add a new reflection shader just days before the release, can we merge this PR?

**Comment by gilbertohasnofb** [comment]
@onox wasn't there still an issue with the pontoon and the back tip of the fuselage? @wlbragg do you have some idea about these?

**Comment by onox** [comment]
I think @wlbragg did some work on the pontoon that seem to have fixed it.

**Comment by gilbertohasnofb** [comment]
I don't think my FGDATA is up to date, I was having some issues with my installation recently. If you want to merge this, could you take a quick look if everything is fine using the most recent FGDATA?

**Comment by onox** [comment]
Pontoons look fine:

fgfs-screen-024

**Comment by HHS81** [comment]
@onox 

> Assuming Thorsten and @HHS81 aren't going to add a new reflection shader just days before the release, can we merge this PR?

No, time is too short now. But I have very propably a fix for the grey reflection issue, so reflection-type="2" will be obsolete.
Unless you are using this type, it will maybe need some tuning of reflection strength later to your liking.

**Comment by onox** [comment]
`bumpspec.eff` seems to use type 1.

**Comment by wlbragg** [comment]
I can confirm the pontoon issue was fixed.

**Comment by wlbragg** [comment]
Do I have time to finish the bush wheel improvements or I'll ask this way, how much time before we can't get a PR in this release?

**Comment by gilbertohasnofb** [comment]
@wlbragg Stuart just wrote us that if we have the release done before Thursday 2200 GMT he will be able to have it merged to the next release. So we do have a bit of time, but ideally we shouldn't message him at 21:59 on Thursday evening :wink:

**Comment by wlbragg** [comment]
I'll try to do it before my night is over, that is in the next few hours. I just have to figure out where it is all at.

**Comment by gilbertohasnofb** [comment]
@wlbragg :+1: 

@onox I also want to take a look on one more thing if we would have time, I seem to have spotted a bug in the water contamination system, but I need a fresher mind to take a look at it so I am thinking about working on it tomorrow during the day. So what do you think if we check all these things (this PR and potentially the water contamination one as well) tomorrow and have a release by the evening? Would you be available?

**Comment by onox** [comment]
Tomorrow I'm available in the evening.

**Comment by gilbertohasnofb** [comment]
@onox Great, so I will work on it during the day and create a PR if found necessary. I will probably be around in the evening as well in case we need to discuss anything

**Comment by onox** [comment]
Sounds good 👍

**Pull request merged**
