### PR TITLE
FDM adjustments: elevator stall table, side force rudder, adverse yaw

### PR DESCRIPTION
**Pull request by dany93**
See issue https://github.com/c172p-team/c172p-detailed/issues/944

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
This looks good to me. I will just leave this opened for a short while to see if someone with flying experience would like to test it, else I will merge it in a couple of days, is that fine with you @dany93 ?

**Comment by dany93** [comment]
Fine, thank you @gilbertohasnofb

**Comment by gilbertohasnofb** [comment]
So perhaps @tigert @Juanvvc @stuartbuchanan or others with flying experience could give this a try?

**Comment by legoboyvdlp** [comment]
Excellent... I've always felt there was a bit too much adverse yaw, making it a little difficult for those of us without rudder pedals :)

**Comment by gilbertohasnofb** [comment]
I am merging this now, if someone has any input for improvements then we can add those in the future. In the meantime, thanks a lot, @dany93

**Comment by dany93** [comment]
Thank you @gilbertohasnofb, hi @onox .

**Pull request merged**
