### PR TITLE
Bug 875 - More realistic bush wheels and tires

### LINKED ISSUE #875: More realistic bush wheels and tires
The bush tire and rim are not realistic. The tire should be a slick and the rim should be closer to the size of the default tire and could stand a better texture appropriate to a bush tire.

@gilbertohasnofb if you want to research the look of a bush tire and rim and make the texture, I'll apply it and fix the rim size. Or I can also research it and provide a picture for reference.

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #875 

OK, I think this is finished. I tested the normal and damaged 26 and 36 inch bush tire and rims.
Please someone else test before merging. I had to cleanup a bunch of internal Blender material mappings. It's stuff I have learned how to organize since I was last in these files. In reality, virtually every blender file in this project could stand to be cleaned and organized (massive job).

Watch for any irregularities in damage parts.

### CODE REVIEW

**Comment by onox** [comment]
Tires look OK 👍

**Comment by gilbertohasnofb** [comment]
@wlbragg they look great to me. So is this ready to be merged or do you still plan to work on it?

**Comment by gilbertohasnofb** [comment]
@onox thanks for merging this, I updated the list of features to include this and the fuel contamination improvements. So now we just need to wait for @dg-505 to work on the tutorial and checklists tonight, as well as consider that other opened PR about the bumpspec. Looking good :smiley: :+1:

**Comment by gilbertohasnofb** [comment]
> Remove from project, perhaps?

What do you mean, @legoboyvdlp?

**Comment by legoboyvdlp** [comment]
Apologies - should have been more clear. There are various closed issues in the exterior 3D project, I was wondering if they should be removed.

**Comment by onox** [comment]
Thanks for mentioning it, I've removed the closed issues from the project.

**Pull request merged**
