### PR TITLE
More sound improvements

### LINKED ISSUE #779: Better propeller sound
Create better propeller sound as the `wasp.wav` isn't really a very good quality sound

### LINKED ISSUE #1021: Add movement and sound for Primer
First, I consider it as a *low-priority* enhancement.

 Please see the video from 1:36 about priming the engine, in real world primer not just 'In' and 'Out' two state, it also has a process from out to in, and also a 'lock' progress. 

https://www.youtube.com/watch?v=HcomtC_DSlc

To enhance the reality, I suggest add a movement for primer and sound as well.

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
Fixes #779
Fixes #1021

This PR should fix all our sound issues. It mainly improves the engine sounds using a CC0 licensed recording from a 172 cockpit. Here is the changelog:

* adds a new and better engine sound based on real recordings 
* adds a new idle engine sound which is crossfaded with the regular engine sound so that it is only perceived at low RPMs. It has that characteristic "rumbling" of low-RPM
* adds new crank and engine start sounds, much improved from the default ones. In particular, the engine now starts with a large "thump" just like a real engine does
* adds a new sound for when the engine is cut, also based on a real 172 recording
* adds new sounds to the primer lever, a low volume squeak sound based on videos (but created using other methods as those reference sources did not have friendly licenses)
* animates the primer and carb heat levers so that they don't just flip between their extreme positions

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp wrote:

> Also, freesound.org is quite useful:
> https://freesound.org/people/JLWSound/sounds/322321/

That was a gold mine, many, many thanks for pointing that file out to me!

@onox @wlbragg @dany93 Would you guys take it for a spin and let me know what you think? It's not a problem if any of you is not comfortable with feedback on sounds, just let me know if something grabs your attention or if something sounds strange or worse than before in your opinions.

**Comment by gilbertohasnofb** [comment]
:warning: :warning: :warning: I just found some bugs that need fixing

**Comment by gilbertohasnofb** [comment]
Done, this is ready again for testing and merging.

**Comment by wlbragg** [comment]
@gilbertohasnofb how cool, I'll pull it and test.

**Comment by gilbertohasnofb** [comment]
Thanks!

**Comment by wlbragg** [comment]
Really nice, what a great addition! It is amazing how much changing something like sound can make in the feel of the simulation. I really like these sound changes. :+1:

You need more testing (from others) or are you ready to have it merged?

**Comment by gilbertohasnofb** [comment]
I just want to see one more thing concerning the pitch of the engine sound, perhaps do a minor tweak. Thanks for testing this, really appreciate it

**Comment by wlbragg** [comment]
@gilbertohasnofb Are we supposed to hear the electrical whine (I don't know if that is gyro or what) from the external view?

>adds new sounds to the primer lever, a low volume squeak sound
I don't hear this?

**Comment by wlbragg** [comment]
>>adds new sounds to the primer lever, a low volume squeak sound

>I don't hear this?

Oops, yeah I do, I switched to a branch without the new sounds.

Oh, you break my engine with the clunk at shutoff you have to buy me a new one! :laughing:

**Comment by wlbragg** [comment]
And the whine is also gone in the exterior view in this bug-779 branch.

**Comment by gilbertohasnofb** [comment]
Ok, this is really ready now, I just adjusted the pitch of the engine sound a tiny bit. 

@wlbragg great that all issues disappeared, is there anything else?

> Oh, you break my engine with the clunk at shutoff you have to buy me a new one! laughing

Hehe! That's just the rumbling from the idle sound, these things do sound like that

**Comment by wlbragg** [comment]
>is there anything else?

"Sounds" good to me, nice upgrade!

**Comment by dany93** [comment]
I just tested it during a short time, but it sounds very good. Important improvement.
I don't know the real sound of the Cessna 172, but if that's the result from real recordings, no complaints.

**Comment by gilbertohasnofb** [comment]
@dany93 Thanks Dany, I really appreciate it.

**Comment by legoboyvdlp** [comment]
@gilbertohasnofb no problem, I was searching for the A320, and came across the sound ;)

There is a lot, lot more on that site!

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp I know that site well, I did use it for more than half of the sounds I created. But that specific one was really super useful, thanks a lot.

**Comment by onox** [comment]
@gilbertohasnofb The new sounds sound amazing! I really like it :smile: One small thing though: could you perhaps add a `README.md` file to the `Sounds/` folder and mention the link and license (CC0) of the files? You might want to mention the repair sound as well (https://github.com/c172p-team/c172p-detailed/issues/273#issuecomment-113788661)

You can add it in this branch and create a new PR.

**Comment by gilbertohasnofb** [comment]
Thank you so much, @onox! As for the `README.md`, I will get that done by today, I should push a PR with that in the evening.

**Pull request merged**
